encoding: utf-8
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: America/New_York

title: Open Wayside

tipue_search:
  include:
    pages: true
    collections: [solutions,libraries]
  exclude:
    files: [search.html, index.md]
    tags: []
    categories: []

menu:
- title: Home
  url: /
- title: Solutions
  url: /solutions/
- title: Libraries
  url: /libraries/
- title: Search
  url: /search/
