encoding: utf-8
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: America/New_York

menu:
- title: Home
  url: /
- title: Solutions
  url: /solutions/
- title: Search
  url: /Search/
